### ISSUE TITLE
Some form CSS fixes

### ISSUE THREAD

**Issue by niksy** [nathansmith/formalize#1]
Hi Nathan,

Here are some of the fixes for IE CSS bugs, maybe you should try to implement them if you want:

http://is.gd/eXpIq
http://is.gd/eXtvr
http://is.gd/g7NDc

**Comment by nathansmith** [comment]
Thanks. Good call on textarea overflow. I've added that. By the way: I already had ::-moz-focus-inner, at the top of formalize.css. As for legends, well, I don't really use them, and they don't seem to be that popular, so I'll wait to see if more people demand that. :)

**Comment by niksy** [comment]
Oops, haven’t noticed that :)
Nevertheless, WebKit also has some problems regarding button element, you can read everything about it [here](http://is.gd/g8kXL).

**Comment by nathansmith** [comment]
I already solved those problems :)
