### ISSUE TITLE
Placeholder text hidden after form submission, even though something else stopped the submission

### ISSUE THREAD

**Issue by simshaun** [nathansmith/formalize#10]
Upon submission, the **placeholder** method clears out any inputs that still have the original placeholder text.

The problem is something else might prevent form submission (such as form validation), in which case all of the placeholder text is gone.

The only thing I can think of that might solve this is to add a timeout to the submit event. The timeout would restore all placeholder text, if necessary. I'm not sure if this is the best way though, since it creates a race condition. If the timeout somehow fires before the form submission is initiated, then the placeholder text would be in the POST data.  Ideas?

**Comment by rafi** [comment]
This will happen as well if the form is submitted using ajax. No ideas yet..

**Comment by nathansmith** [comment]
Actually, if I'm understanding the problem correctly, the solution should be as simple as re-calling the init function...

FORMALIZE.init.placeholder();

That should change all empty placeholders back to their initial state, with grayed-out text, etc. Let me know if that works for you.

**Comment by simshaun** [comment]
It's not automatic, but yep that gets the job done. Thanks.

FWIW, anybody using Jorn's jquery validation plugin can call that method from within the invalidHandler option, like so: <pre><code>invalidHandler: function() {
    FORMALIZE.init.placeholder();
}</code></pre>

**Comment by nathansmith** [comment]
Nice, glad that works! I structured it like that for just such an edge case :)

**Comment by simshaun** [comment]
I spoke too soon.

It's early in the AM, so my brain could be confuddled, but it seems `FORMALIZE.init.placeholder();` fails to work for any subsequent calls after being called once. After I submit (and cancel the form submission) twice, I see the placeholder text being added back but being removed right after.

I don't think it's limited to my implementation either. Take the _jquery_errors.html_ demo and modify the form onsubmit attribute to `onsubmit="FORMALIZE.init.placeholder(); return false;"`. It doesn't _appear_ to be working, but if you hold down enter on a field, you will see that it is restoring the placeholder text (for me, I see it on the email field) but removing it right afterwards.

The odd part is, in my implementation, the placeholder text actually is being restored and stays until I try to submit a second time and the form submission is stopped.

In the _jquery_errors.html_ demo, it never _appears_ to restore the placeholder text at all.

**Comment by nathansmith** [comment]
That's because of lines 119 to 121...

<pre>
if (el.val() === text) {
  el.val('').removeClass('placeholder_text');
}
</pre>


That keeps the form from submitting placeholder text to the server. For browsers that don't natively support HTML5 placeholder text, this would be bad because it'd give a false positive, as if the user had typed in the placeholder text.

So I think you might need to edit the formalize JS file itself, to do exactly what you need it to do. Or, simpler, you could just not use placeholders on elements that get validated on the client-side.

**Comment by simshaun** [comment]
That it removes placeholder text before submission is good. That's not the issue..

What I'm trying to do is manually reinstate placeholder text _after_ I stop the form submission.

I call `FORMALIZE.init.placeholder();` manually after stopping form submission, which works the **first** time.  But, the second time I stop form submission and then on, it doesn't work.

**Comment by simshaun** [comment]
The issue is that `FORMALIZE.init.placeholder();` binds a new onSubmit event to the form every time its called.

I've fixed it one way by added a class to the form and making sure that class doesn't exist before rebinding the events. Have made a pull request for it. Check it out and let me know if you see any potential issues with it.  https://github.com/nathansmith/formalize/pull/13
