### ISSUE TITLE
compass support

### ISSUE THREAD

**Issue by chrisdrackett** [nathansmith/formalize#14]
I've been working on getting this working with compass and did the following. Its just a start, but wasn't sure if it would be useful in the future if you want to add compass CSS support:

https://gist.github.com/841193

**Comment by nathansmith** [comment]
Cool, thanks.

I've actually done a Sass version for usage in a project at HP (where I work).

Do you think it'd be beneficial to have a *.sass file in the Formalize download itself?

**Comment by bryanveloso** [comment]
Definitely. It'd make it easier to mix-in. :]

**Comment by chrisdrackett** [comment]
er, I wrote a comment here earler.. where did it go?

what I said was that for the code I use in compass (based on the gist above) I'm removing all color, border color and type family styles. I guess I'm using it as more of a "reset" and then doing my own styles with compass.

one thing I've thought of doing is making the typography and colors options within compass:

```
+formalize(<color>,<border-radius>,<font-family>,<font-size>)
```

hm.. need more time in the day...

**Comment by nathansmith** [comment]
Chris -- That's a bit over my head, but I think at the very least, I'll add a _formalize.sass file to the download, so people can sprinkle it in, as needed.

**Comment by chrisdrackett** [comment]
no worries, its on my list of todo's, so it'll maybe be done sometime this decade ;)

**Comment by nathansmith** [comment]
Just wanted to let you know that I've added a _formalize.sass file to the repo, so people can use that as a starting point for their Sass / Compass projects.
