### ISSUE TITLE
Blue border around radio button with focus in Opera

### ISSUE THREAD

**Issue by aBrookland** [nathansmith/formalize#18]
Hi,

I've just come accross Formalize and I've been testing it on a new website we're building.

I really like this as it's always been an issue making sure form elements fit into the design cross browser so thanks so much for releasing it.

Just came across a minor issue though - in Opera (I've tested with 11.01) the radio buttons have the blue border when you click on them but no other browser does that (tried Firefox 3.6, IE 8, Chrome 9 and Safari 5 all on Windows). Not so bothered that it's different behaviour than the others but mostly don't like it because the blue border is square which just looks plain wrong.

Cheers,

Alan

**Comment by nathansmith** [comment]
You're right. That is kinda gross. I've added an override to get rid of the glow for inputs of type = checkbox / radio.
