### ISSUE TITLE
Webkit select isn't wide enough without an optgroup

### ISSUE THREAD

**Issue by wadewinningham** [nathansmith/formalize#2]
Longer options in a select in webkit browsers end up overlaying the select_arrow.gif image for the if you don't have them wrapped in an optgroup. An optgroup ends up adding the necessary padding.

Since FireFox and IE cover this image up with their own arrows, adding padding-right ends up sliding the select_arrow.gif image into view and screwing up their display.

**Comment by nathansmith** [comment]
Ah, phooey. Good catch!

I've patched this via JavaScript, in lieu of there being a pure-CSS solution (yet).
