### ISSUE TITLE
box-sizing IE6,7,8 and textarea width 100% + borders

### ISSUE THREAD

**Issue by christiaan** [nathansmith/formalize#22]
When dealing with browsers that don't support the CSS property "box-sizing" (IE 6,7,8)
when specifying a textarea with width : 100% and supplying a border the textarea actually grows wider then the 100% as the 100% width is minus the border.

A trick i've been applying myself to circumvent this problem is done as follows.
Wrap the textarea in a label tag, set the label to display block make the textarea 100% width without any paddings or border.
The label + textarea then acts as a real block element.

See https://gist.github.com/884735 for an example of the behavior.

**Comment by nathansmith** [comment]
This is already built into Formalize, and is only needed for IE7. IE6 gets its box-model incorrect, so it actually (accidentally) does support box-sizing. And IE8 natively supports box-sizing already. See lines 35 to 43 here...

https://github.com/nathansmith/formalize/blob/master/assets/javascripts/jquery.formalize.js
