### ISSUE TITLE
Placeholder text is black in Firefox 4

### ISSUE THREAD

**Issue by noahm** [nathansmith/formalize#23]
Tested on OS X, the color attribute of input elements applies both to an entered value and the placeholder. I added the following to the stylesheet and it seemed to at least fix the two instances of placeholder text in the demo:
`:-moz-placeholder { color: #777 !important; }`

(edit: use !important and it's good with just the bare pseudo-selector)

**Comment by nathansmith** [comment]
Good catch. Fixed and pushed. I just targeted input and textarea specifically, so that it can still be overridden (easier than working against !important).
