### ISSUE TITLE
Non-multiple selects with size attr get wrong height

### ISSUE THREAD

**Issue by Mtillmann** [nathansmith/formalize#24]
When you have a select element that isn't multiple but has a size attr it will be redendere only one unit high. This fixes the behaviour at last for modern browsers:

`textarea,
select[multiple], select[size] {
  height: auto;
}`

**Comment by nathansmith** [comment]
Good catch! Fixed, and pushed.

**Comment by Mtillmann** [comment]
very nice, thank you!
