### ISSUE TITLE
Possible to exclude a certain set of inputs?

### ISSUE THREAD

**Issue by markquezada** [nathansmith/formalize#28]
First off, thanks for this great little utility.

I was wondering if it's possible to exclude certain types of inputs. For example, I have a special input button that i'd like formalize _not_ to style since it has some custom styling attached already. Is there any way to keep formalize from affecting these inputs? It's a bit clumsy to try to do it by redefining css properties simply for the sake of negating the effects of formalize.

I'd imagine it would be hard to provide an array of excluded classes (or something similar) since formalize is automatically run on dom ready. Thoughts?

**Comment by nathansmith** [comment]
Yeah, Formalize is mostly CSS, so the styling will take effect, even without the JavaScript (which only exists to patch older browsers to handle HTML5 aspects).
