### ISSUE TITLE
Form field button doesn't work in IE7/8 and the button isn't styled in a useful way.

### ISSUE THREAD

**Issue by axefrog** [nathansmith/formalize#30]
Not too worried about IE7 to be honest, but loads of people still use IE8 and I suspect that it may be the same problem in both. Also, in addition to not working, the buttons come up semi-styled; as in the button shows up, but without text, giving it a tiny width and making it hard to click.

![Screenshot of form field IE7/8](http://content.screencast.com/users/NathanRidley/folders/Jing/media/e2ed612c-e426-4076-a436-d5d1a34df124/2011-06-28_0718.png)

(Everything else seems to be fine in all versions of IE - IE6 styling isn't perfect but it's "good enough", which is all we really care about in old IE versions)

I am testing in [IE Tester](http://www.my-debugbar.com/wiki/IETester/HomePage).

**Comment by axefrog** [comment]
Upon further testing, this appears to be an IETester issue as it worked on an actual IE8 browser and in IE9's older browser engine testing modes (IE7/8 standards modes). I don't have access to a real installation of IE7 but I'm going to assume it probably works, so I'll close this issue.

**Comment by nathansmith** [comment]
Yeah, I just tested on a real install of IE8, and it looked fine.
