### ISSUE TITLE
Feedback from a first time user 

### ISSUE THREAD

**Issue by chrisjacob** [nathansmith/formalize#32]
Hi Nathan,

Thanks for this awesome project - totally saving my bacon!

Just some feedback from my first time implementing.

When I looked at the demo's I saw demo.css, reset.css and text.css... this confused me a little when I went to implement formalize.css as I wasn't sure if I needed those files also (in particular the reset.css ... since I'm using normalize.css).... I ended up not needing either, and removing some styles from normalize.css (https://github.com/necolas/normalize.css).

Also my project already has image replacement happening for buttons so I striped out your styles for buttons...

... I figure this feedback may be useful; since you're so close to the project it's hard to see things at times with "fresh eyes" (i.e. usability testing).

One other idea - consider offering some well tested theme's to lay over the top of formalize'd forms/buttons ... would help people go that one step further ... particularly when client wasn't their form to look "special" :: sigh ::

Cheers,
Chris

**Comment by nathansmith** [comment]
Chris:

Correct, neither reset.css nor text.css are required.

As for themes, formalize.css can be overridden and themed ('tis all just CSS), but nobody has made "well tested themes" to layer over the top of Formalize (yet). :)

**Comment by Gavrisimo** [comment]
Hey Nathan, i would love to get involved in 'theme creating', 'wiki page - how to overwrite a theme' and 'wiki page - how to create your own theme'. :)

Any thoughts?

**Comment by nathansmith** [comment]
Could you write up a draft of it, and send it over to me?
