### ISSUE TITLE
File input not "formalized"

### ISSUE THREAD

**Issue by webxl** [nathansmith/formalize#33]
File upload controls differ drastically among browsers and OS's. I was expecting your library to address that, but I just tried your demo on Chome and IE and the rendered controls don't look at all alike.

Any plans for that?

http://www.appelsiini.net/projects/filestyle

I'm using this jQ plugin right now, but it would be nice if your library included a solution.

**Comment by nathansmith** [comment]
I didn't attempt to style the input type="file" because it would've required obscuring the real input via JS, and I didn't want to artificially replace any elements, just style those that were already present.
