### ISSUE TITLE
IE7/8 Fix Drop-down Width

### ISSUE THREAD

**Issue by shanink** [nathansmith/formalize#34]
I apologize, as this isn't really an issue with Formalize but more of a request? Is it possible to add in a fix for the famous drop-down text cutoff IE7 & 8 deal with? I love Formalize and adding this in would make it even more awesome.

Thanks for listening :) Keep doing what you do!

**Comment by nathansmith** [comment]
Unfortunately there's nothing that can be done about that with CSS. It's an IE problem is deeper-rooted in the browser itself.
