### ISSUE TITLE
placeholder_text in js file

### ISSUE THREAD

**Issue by philwareham** [nathansmith/formalize#35]
Hi Nathan,

In [a recent commit](https://github.com/nathansmith/formalize/commit/c7a99bd7181bff377052e44388c47ee1e07f1e52) you've changed the placeholder class from `.placeholder_text` to `.placeholder-text`, yet the js file is still trying to target the older selector. Needs to be updated I think?

Cheers,
Phil

**Comment by nathansmith** [comment]
Ah, oops. The project I'm on at work has "-" as the standard for word separators (versus "_"). I made a few minor updates to Formalize, but left in the "-" by mistake. Fixed now.
