### ISSUE TITLE
Password placeholder in IE 9 and below

### ISSUE THREAD

**Issue by zinkkrysty** [nathansmith/formalize#38]
The password placeholder is masked in IE 9 and below (because it's using the value attribute), therefore useless. 

A possible solution is to change the type of input to "text" until it's focused, but haven't tested it and maybe gives some other issues.

Here's an example of a plugin that uses some kind of placeholder input, and it's quite good, but can't be used together with formalize:
https://github.com/danielstocks/jQuery-Placeholder

**Comment by nathansmith** [comment]
Ugh, IE. Good times. I feel your pain. :(

So, I tried building a little test case, to change the type="password" to type="text", but it appears that's disabled by the browser, probably for security purposes.

In Chrome:
http://cl.ly/1L2A3W2n3j0q333Z000L

In IE:
http://cl.ly/0d0f2k3N2o332p1D2c1z

That jQuery placeholder plugin operates by replacing the password input with a text input. Do you think it's worth going that route with Formalize, for IE?

**Comment by zinkkrysty** [comment]
You're probably right that it's too much trouble to fix it, but still, IE is still having 40% of the browser market. 

The use case for this fix is also too low (password placeholders) to require a major addition to the code. 

But what about the ability to disable placeholder simulation so it can be handled by other plugins, but keep the rest of the nice formalize code working ? 

Would be a good trade-off in my opinion :)

**Comment by nathansmith** [comment]
Agreed. Fixed. Or rather, not adding faux placeholder to input type="password"...

https://github.com/nathansmith/formalize/commit/0e12ea77dc381bfe5fd9b6d07c5602c796a66fe3
