### ISSUE TITLE
html select box with size=0 doesnt work

### ISSUE THREAD

**Issue by ghost** [nathansmith/formalize#40]
Drupal 7 Form API use the size attribute for every select box. Example:

<select class="country form-select required" id="edit-customer-profile-billing-commerce-customer-address-und-0-country" name="customer_profile_billing[commerce_customer_address][und][0][country]" size="0">

The following code in line 290 overwrite the backround image and make the arrow disapper.
select[size], select[multiple] {
background-image: none;
padding: 0;
}

**Comment by nathansmith** [comment]
Fixed. I addressed it in the *.sass file, and re-generated the *.css file...

https://github.com/nathansmith/formalize/commit/b9528e8b84506c1e28c1e6fdbbfb3f6f1c0f6d53
