### ISSUE TITLE
Firefox: optgroup doesn’t inherit font-family specified for select

### ISSUE THREAD

**Issue by isellsoap** [nathansmith/formalize#41]
In Firefox `optgroup` seems to not inherit the `font-family` specified for `select`. For example Mac OS X uses »Lucida Grande« and Windows 7 uses »MS Shell Dlg« as the final computed value. If you use a serif font on your site this becomes more obvious. `optgroup` needs an explicit font-family declaration.

**Comment by nathansmith** [comment]
Ah, gotcha. Makes more sense here than in your tweet(s). I'll look into that soon. Thanks!

**Comment by nathansmith** [comment]
Fixed...

https://github.com/nathansmith/formalize/commit/f5d2c1726c4e9b35b5a2a97ecefbcab1a3124351
