### ISSUE TITLE
select and vertical-align

### ISSUE THREAD

**Issue by isellsoap** [nathansmith/formalize#43]
Adding a `size` bigger than 1 or `multiple="multiple"` [here](https://github.com/nathansmith/formalize/blob/master/jquery_demo.html#L57) results in [this behaviour](http://img444.imageshack.us/img444/3378/ohnetitel.png). Shouldn’t it be more [like this](http://img207.imageshack.us/img207/8964/ohnetitel2.png)?

A …

``` css
select {
    vertical-align: top;
}
```

… would solve the issue.

**Comment by nathansmith** [comment]
I just made all inputs have `vertical-align: top`, probably best to just do it across the board.

Fixed in this commit...

https://github.com/nathansmith/formalize/commit/a1070a212bce5a90b2a356061cfb94bdf48e5c84
