### ISSUE TITLE
WebKit: background-image on select in combination with size='0'/size='1' and multiple

### ISSUE THREAD

**Issue by isellsoap** [nathansmith/formalize#44]
The code `<select … size="1" multiple="multiple">…</select>` (same happens with size=0) results in [this behaviour](http://img856.imageshack.us/img856/5874/ohnetitel3.png). Adding `select[size='0'][multiple]` and `select[size='1'][multiple]` in [this declaration block](https://github.com/nathansmith/formalize/blob/master/assets/css/formalize.css#L285) would solve the issue.

**Comment by nathansmith** [comment]
Kind of an edge case, (not sure one would _want_ multiple selections in a single height `<select>`).

But, I fixed it...

https://github.com/nathansmith/formalize/commit/a1070a212bce5a90b2a356061cfb94bdf48e5c84
