### ISSUE TITLE
Error compile sass "_formalize.sass"

### ISSUE THREAD

**Issue by Nesta** [nathansmith/formalize#47]
(Line 79: Undefined mixin 'background-image'.)

I do not understand why I get this error, if you could enlighten me I would appreciate. greetings!.

**Comment by nathansmith** [comment]
Are you making sure to include...

`@import compass/css3/gradient`

That is required at the top of the file, in order for `+background` and/or `+background-image` to be recognized.

**Comment by ghost** [comment]
Are you using Compass 0.12.0? The Formalize Sass/Compass file is no longer valid in this version, change the following on line 9:

``` CSS
@import compass/css3/gradient
```

to

``` CSS
@import compass/css3/images
```

And see how that goes.

**Comment by nathansmith** [comment]
I just changed the import to:

`@import compass/css3`

That way, it will "just work," regardless of Compass version.

I pushed the change in this commit:

https://github.com/nathansmith/formalize/commit/a913a8b9deb31082d1b7e7928862da9886645a49
