### ISSUE TITLE
jquery.formalize.min.js -- missing semicolon

### ISSUE THREAD

**Issue by thezoggy** [nathansmith/formalize#48]
the jquery.formalize.min.js version has some sort of error when you use it in the h5bp build script.. loading up the code in jshint shows that there is a missing semicolon

running jquery.formalize.js through closure-compiler-v1346 returns a much different result and works fine.

**Comment by nathansmith** [comment]
I am using UglifyJS for minification, because it yields better compression than Closure compiler.

I'd recommend starting out with uncompressed JavaScript files when using a build tool. That way, the build process can do its own minification, as it concatenates the files.
