### ISSUE TITLE
.placeholder_text {   color:#777 !important; }

### ISSUE THREAD

**Issue by tingletech** [nathansmith/formalize#5]
To get the placeholder_text to show grey in my firefox (Firefox 3.6.11 Max OS), I had to change it to
.placeholder_text {
        color: #777 !important;
}

I loaded these github URLs as resources into jsfiddle
http://github.com/nathansmith/formalize/raw/master/assets/stylesheets/formalize.css
http://github.com/nathansmith/formalize/raw/master/assets/javascripts/formalize.js

Here, the input type="text" shows up black and input w/o type attribute is grey #777
http://jsfiddle.net/GeGbL/

Here, it shows up grey #777 with or without the type="text" because I've set a css rule
.placeholder_text {   color:#777 !important; }
http://jsfiddle.net/4pvHT/

I'm going to create a folder for this inside of my project and keep a version in my bitbucket
http://bitbucket.org/btingle/cpf2html/src
Can I put a 3-clause BSD license, Copyright © 2010 nathansmith in the formalize sub-directory?

I am very happy I found this, I was planning to write the placeholder-for-firefox my project and now I don't have to, plus that is a totally bitchin option/select box and search button.  Thanks.

**Comment by nathansmith** [comment]
Thanks for the heads up. I just pushed a fix, so you won't have to worry about !important. Also, I'm fine with you using Formalize in your own projects. No worries there, it's meant to be free.
