### ISSUE TITLE
Problems to work on IE9

### ISSUE THREAD

**Issue by diegofersan** [nathansmith/formalize#54]
Guys, I've problems to do work on IE9 the Jquery version. The validation just doesn't work. Someone had this problem and can help me?

Thanks.

**Comment by nathansmith** [comment]
Formalize doesn't add validation.

Any validation you're seeing in other browsers is native to that particular browser.

For example… Chrome and Firefox both show tooltip bubbles if a field doesn't meet valid criteria, such as an email address without the `@` character, etc.

But, this functionality is not built into Formalize's code anywhere. IE9 simply doesn't have that natively.

If you are looking for a jQuery validation plugin, this is the semi-official one (used by Microsoft)…

http://bassistance.de/jquery-plugins/jquery-plugin-validation/
