### ISSUE TITLE
Add .button selector to button styles

### ISSUE THREAD

**Issue by mbrochh** [nathansmith/formalize#55]
Hey it would be super awesome if you could add .button as a selector to all those button styles (i.e. here: https://github.com/nathansmith/formalize/blob/master/assets/css/formalize.css#L66)

We often use `<a class="button">` to create links that look just like buttons. We are using formalize as a submodule in our project and therefore we don't want to make any changes to it (we have formalize.css symlinked), so currently we have to copy all those button styles ONLY to add that tiny little bit.

Is there a good reason to not add that selector?

**Comment by nathansmith** [comment]
You know, I actually found myself doing that via Sass…

```
.button
  @extend button
```

But yeah, no reason that can't just be part of Formalize.

Do you think `class="button"` is too generic? Like, should that be `formalize-button`?

I'm fine with "button" but am just wondering if that might have some "namespace collisions" with other people's code.

**Comment by mbrochh** [comment]
Oh wow I wasn't aware that this is so easy with SASS.

But yea, not everyone uses SASS and formalize-button is probably a good
idea!
On Jul 3, 2012 2:02 AM, "Nathan Smith" <
reply@reply.github.com>
wrote:

**Comment by nathansmith** [comment]
@mbrochh — Just wanted to let you know I finally got around to implementing this (browser testing in old IE, and accounting for a disabled link button via JS took awhile). It was added in this changeset…

https://github.com/nathansmith/formalize/commit/7b038c675ef7d7ec6bca47f6f89dfa6c8afcc1ae

Basically, just do:

```
<a href="…" class="button">Link Button</a>
```

And, for disabled:

```
<a href="…" class="button_disabled">Link Button</a>
```
