### ISSUE TITLE
Please create a .scss file as well

### ISSUE THREAD

**Issue by jensimmons** [nathansmith/formalize#58]
I'd love to have a .scss file. Many of us use Sass with .scss, instead of .sass.

**Comment by nathansmith** [comment]
Assuming you're using Formalize via an `@import`, the *.sass version should work just as well as if it was *.scss.

So, I guess I'm wondering – What's the use-case for having it as *.scss? I'm not saying "no," just saying "Help me to understand."

**Comment by jensimmons** [comment]
Sometimes I'll fork Formalize, instead of overriding it's visual styles. Depends on the project. But when I want to fork it, I have to make a .scss file so we can use it. Today I spent a while converting that CSS into SCSS, putting your groovy comments back in, sassifying some of the code. Tedious. I wondered, hey how come there's not a .scss file here already? That would be handy. So I thought I'd open an issue.

Also, THANKS! Reading through the code line by line again today made me realize how handy this library is.

**Comment by nathansmith** [comment]
Just posting here to let you know I haven't forgotten about this. I still have the email thread star'd in my inbox.

But, I'm trying to think of a way to be able to write *.sass and have it also spit out a *.scss file. I'm thinking maybe doing some sort of regex, but haven't had the time to experiment with that approach.

**Comment by smizell** [comment]
I was looking at this too. Looks like there is a way to convert back and forth between *.sass and *.scss.

http://sass-lang.com/docs/yardoc/file.SASS_REFERENCE.html

**Comment by nathansmith** [comment]
Nice, I'll check if I can just make this part of my normal build process.

**Comment by jensimmons** [comment]
Oh, that would be handy. Easy to make. Flexible for all kinds of uses. :) Thanks.

**Comment by nathansmith** [comment]
That convert command worked like a charm. Added in this commit…

https://github.com/nathansmith/formalize/commit/e33fb647d7d9365d5f7ec88e800aca7b35ae5c89

**Comment by jensimmons** [comment]
Sweet! Thanks Nathan. :)
