### ISSUE TITLE
Opera textarea placeholder dont show up

### ISSUE THREAD

**Issue by neonailol** [nathansmith/formalize#6]
in Opera10/11 placeholder in textarea don't show up

i changed 
    var PLACEHOLDER_SUPPORTED = 'placeholder' in document.createElement('input')
to
    var PLACEHOLDER_SUPPORTED = 'placeholder' in document.createElement('input') && 'placeholder' in document.createElement('textarea');

and then it shown

**Comment by nathansmith** [comment]
@Neonailol -- It works for me. I was unable to reproduce the problem you reported, using Opera 10.63 on OS X.

Please double-check and confirm there is a problem with the demo itself...

http://host.sonspring.com/formalize

**Comment by nathansmith** [comment]
@Neonailol -- Actually, I just confirmed that this is broken in Opera 11. I'm now trying to determine if placeholder="..." is supposed to be supported on textarea, and if Opera has a bug, or if it was removed from the HTML5 spec.

**Comment by nathansmith** [comment]
Update: I've been able to confirm this is a bug in Opera 11. A bug report has been filed, so I'm not going to patch this with JS, as it will likely be address soon in an Opera point-release, after which I would have to remove the patch anyway.
