### ISSUE TITLE
Demo pages don't work in IE9 or firefox 19/20 for me?

### ISSUE THREAD

**Issue by thomas-frantz** [nathansmith/formalize#62]
I found this originally on chrome, and it looked great. I tried it on Firefox 19 (And later 20), as well as IE9, and it doesn't seem to work at all (All of the elements in the demo pages, doesn't seem to matter which one, look like regular unstyled form elements.). I can only speak for Chrome / FF 19 and 20 / IE9, and it only works on Chrome.

To give you an example of what I mean, on Chrome the datetime input box looks like a calendar and time selector, with a dropdown calendar inside of it. On firefox/ie it's just a plain text input box.

I've had several friends try it out, and have completely disabled all of my addons on firefox.

**Comment by nathansmith** [comment]
Are you referring to the `<select>` drop-downs?

Those are only fully style-able in WebKit based browsers.

If you're referring to the inputs for…
- Date
- Month
- Range

…etc.

Those are being rendered natively by Chrome. I didn't add any JavaScript or CSS to get that "extra" functionality. Firefox simply doesn't do anything special for those types, treating them as basic text inputs.

**Comment by thomas-frantz** [comment]
Ah, I wasn't aware of that. Guess this is a non-issue then. (And actually was referring to both)

Thanks!

**Comment by nathansmith** [comment]
Yeah, I didn't want to mess with trying to get all browsers to behave that way, when how to treat HTML5 inputs is still in a state of flux.

Eventually, we'll get that functionality "for free" from all browsers (hopefully). And, in the meantime there are things like jQuery UI's calendar that get the job. Didn't want to reinvent the wheel, just wanted to provide (in as much as possible) a consistent look & feel.

**Comment by thomas-frantz** [comment]
Yeah I can't blame you there. It will be nice when they get all that sorted out and it's supported across all the browsers without the need for external workarounds and such. Though I hope they make them able to be styled nicely, or else people might still default to jQuery UI calenders and such.

**Comment by nathansmith** [comment]
Agreed. Right now the styling is a little hit-or-miss, especially considering it looks a lot different depending on Windows / Mac / Linux, etc.
