### ISSUE TITLE
IE10 - Select Boxes not styled correctly

### ISSUE THREAD

**Issue by KyleRoss** [nathansmith/formalize#64]
On IE 10, the select boxes are not styled correctly and the default browser arrow displays instead of the custom arrow included in formalize.

**Comment by nathansmith** [comment]
Unfortunately, the custom arrow only works in WebKit based browsers.

I'm hoping that, at some point, other browsers will allow for better styling of `<select>`.

**Comment by KyleRoss** [comment]
Didn't even think of that when I was developing. You're right, thanks for the update.

**Comment by yvetteu** [comment]
I'm working on a Drupal site that's using formalize. For me, the default arrow is being removed completely in IE10, but not replaced. So I have no arrows in my select boxes in IE10.

**Comment by nathansmith** [comment]
@yvetteu There might be something else in another CSS file interfering.

This is what I see in IE10 for Formalize.

# 

**Screenshot::**

http://cl.ly/image/0o011p0W292s

**Comment by yvetteu** [comment]
@nathansmith Thanks! After I posted, I removed the formalize.css file to test and saw that it was still happening. I couldn't find anything else that should be doing that, so I added this temporarily until I can figure it out:

select::-ms-expand {
    display: block !important;
}

**Comment by nathansmith** [comment]
Okay, glad it worked out.

By the way, I do have something sort of ruminating in the back of my head for a "Formalize 2.0" that will include more/better styling of selects in IE.

But, work on that is contingent on workload for day job, kids not being sick, etc.

So, don't hold your breath. :)

# 

This is the "form reset" I've been using on client projects lately…

https://gist.github.com/nathansmith/1599212

Then, I build the styles back up from there.

I offer it without warrantee, subject to change, void where prohibited, your mileage may vary, etc.
