### ISSUE TITLE
Formalize along with script loaders

### ISSUE THREAD

**Issue by simshaun** [nathansmith/formalize#7]
I'm using LABjs to load Formalize in parallel with other scripts.  Formalize in particular was causing an error.

The cause of the error is that the document ready block is at the top of the script instead of the bottom. When integrated with LABjs, the document **may** be ready before the FORMALIZE plugin becomes available. In other words, FORMALIZE.go() is being called before we know for sure that FORMALIZE.go() is available.

The solution is simple. Move this block to the bottom of the script:

<pre><code>// Automatically calls all functions in FORMALIZE.init
jQuery(document).ready(function() {
    FORMALIZE.go();
});</code></pre>

That ensures that the document is indeed ready, but also that the formalize plugin is available.

**Comment by nathansmith** [comment]
Good catch. I've updated all the JS files with this change.
