### ISSUE TITLE
jQuery.browser removed in jQuery since version 1.9 - Uncaught Exception

### ISSUE THREAD

**Issue by rbulto** [nathansmith/formalize#75]
Hi there!

The following statements trigger an "Uncaught TypeError: Cannot read property 'msie' of undefined" exception with jQuery 1.9 and newer since jQuery.browser has been deprecated since jQuery 1.3 and finally removed in 1.9 (http://jquery.com/upgrade-guide/1.9/#jquery-browser-removed).

var IE6 = !!($.browser.msie && parseInt($.browser.version, 10) === 6);
var IE7 = !!($.browser.msie && parseInt($.browser.version, 10) === 7);

Is this project still active?

Thanks,

**Comment by thezoggy** [comment]
https://github.com/nathansmith/formalize/branches

not touched in 4 years... so probably not.

**Comment by nathansmith** [comment]
@rbulto What file are you seeing this in?

I haven't used `$.browser.msie` in awhile.

For example, that doesn't appear anywhere in the jQuery flavored file…

https://github.com/nathansmith/formalize/blob/master/assets/js/jquery.formalize.js
