### ISSUE TITLE
Autofocus + Placeholder

### ISSUE THREAD

**Issue by simshaun** [nathansmith/formalize#8]
If you have a text input that has a placeholder value and is set to autofocus, upon loading the page the input will be focused and the placeholder text highlighted, instead of the placeholder text disappearing.

I can't decide whether this is an issue or not. I think I would prefer the placeholder text to disappear. Thoughts?

**Comment by nathansmith** [comment]
Ah, good catch. I've changed it from .select() to .focus() instead. Problem fixed :)
