### ISSUE TITLE
placeholder_text class not removed upon submit

### ISSUE THREAD

**Issue by simshaun** [nathansmith/formalize#9]
I've got client-side validation wired in to a form.  Upon error, it prevents form submission.  Any fields with a placeholder that are not changed are automatically emptied by formalize on form submission, but retain the _placeholder_text_ class.  (Meaning, as I'm fixing my form errors, if I type something in one of those fields that had placeholder text, what I type is gray in color.)

In short, the _placeholder_text_ class needs to be removed from fields upon form submission, just in case the submission is prevented by something else.

**Comment by nathansmith** [comment]
Ah, good catch, I'll fix this now.
